### PR TITLE
Add RU_864_870 frequency plan to support LoRaWAN in Russia

### PR DESCRIPTION
**Pull request by belovictor**
This pull request adds support for RU_864_870 frequency plan to support LoRaWAN in Russia. It includes a fix to brocaar library which was included into TTN code before the valid RU_864_870 was implemented in it and also updates version of api/protocol/lorawan dependency to the new one which has RU_864_870 in the list.

### CODE REVIEW

**Comment by belovictor** [comment]
All tests run fine on my side. Looks like a problem in build system again - something about certs :-(

**Comment by belovictor** [comment]
Just double checked:
GOARCH=amd64 make test
go test ./amqp ./api/pool ./cmd ./core/band ./core/broker ./core/component ./core/discovery ./core/discovery/announcement ./core/handler ./core/handler/application ./core/handler/cayennelpp ./core/handler/device ./core/handler/functions ./core/networkserver ./core/networkserver/device ./core/proxy ./core/router ./core/router/gateway ./core/storage ./core/types ./mqtt ./ttnctl/util ./utils/fcnt ./utils/otaa ./utils/parse ./utils/random ./utils/security ./utils/toa
ok  	github.com/TheThingsNetwork/ttn/amqp	0.875s
ok  	github.com/TheThingsNetwork/ttn/api/pool	1.632s
ok  	github.com/TheThingsNetwork/ttn/cmd	0.601s
ok  	github.com/TheThingsNetwork/ttn/core/band	0.034s
ok  	github.com/TheThingsNetwork/ttn/core/broker	0.636s
ok  	github.com/TheThingsNetwork/ttn/core/component	2.482s
ok  	github.com/TheThingsNetwork/ttn/core/discovery	0.262s
ok  	github.com/TheThingsNetwork/ttn/core/discovery/announcement	0.303s
ok  	github.com/TheThingsNetwork/ttn/core/handler	2.718s
ok  	github.com/TheThingsNetwork/ttn/core/handler/application	0.036s
ok  	github.com/TheThingsNetwork/ttn/core/handler/cayennelpp	0.030s
ok  	github.com/TheThingsNetwork/ttn/core/handler/device	0.045s
ok  	github.com/TheThingsNetwork/ttn/core/handler/functions	0.044s
ok  	github.com/TheThingsNetwork/ttn/core/networkserver	0.618s
ok  	github.com/TheThingsNetwork/ttn/core/networkserver/device	0.052s
ok  	github.com/TheThingsNetwork/ttn/core/proxy	0.038s
ok  	github.com/TheThingsNetwork/ttn/core/router	0.355s
ok  	github.com/TheThingsNetwork/ttn/core/router/gateway	0.953s
ok  	github.com/TheThingsNetwork/ttn/core/storage	0.109s
ok  	github.com/TheThingsNetwork/ttn/core/types	0.039s
ok  	github.com/TheThingsNetwork/ttn/mqtt	2.408s
ok  	github.com/TheThingsNetwork/ttn/ttnctl/util	0.801s
ok  	github.com/TheThingsNetwork/ttn/utils/fcnt	0.010s
ok  	github.com/TheThingsNetwork/ttn/utils/otaa	0.034s
ok  	github.com/TheThingsNetwork/ttn/utils/parse	0.012s
ok  	github.com/TheThingsNetwork/ttn/utils/random	0.024s
ok  	github.com/TheThingsNetwork/ttn/utils/security	0.066s
ok  	github.com/TheThingsNetwork/ttn/utils/toa	0.021s

**Comment by htdvisser** [comment]
We're waiting for a few more changes in github.com/TheThingsNetwork/api and then will update the entire dependency.

**Comment by htdvisser** [comment]
I fixed `gencerts.sh` and re-generated the development certificates.

**Comment by htdvisser** [comment]
I rebased the pull request on top of the changes we made. Should be ok now.

**Comment by belovictor** [comment]
Wow. Thanks a lot!

**Pull request merged**
