### PR TITLE
Use plaintext instead of js(on)

### PR DESCRIPTION
**Pull request by FokkeZB**
Comments in JSON do not render well

### CODE REVIEW

**Comment by htdvisser** [comment]
For that exact reason, these comments use `js`, not `json`. This renders fine, as you can see in this screenshot:

screen shot 2016-11-29 at 20 19 04

**Comment by FokkeZB** [comment]
Unfortunately not in rouge, what jekyll uses: https://www.thethingsnetwork.org/docs/v2-preview/mqtt/#uplink-messages

**Comment by htdvisser** [comment]
Can't you just configure `redcarpet` and `pygments`?

**Comment by FokkeZB** [comment]
Yes, if that is closer to what Github renders we should indeed. Will give it a try.

**Comment by FokkeZB** [comment]
Created https://github.com/TheThingsNetwork/docs/issues/100

**Pull request closed without merging**
