### PR TITLE
use bin path for govendor

### PR DESCRIPTION
**Pull request by joscha**
Fixes #521

### CODE REVIEW

**Comment by rvolosatovs** [comment]
your env variable name is wrong - it should be `GOPATH`, not `GO_PATH` (that is probably where your issue stems from)

**Comment by joscha** [comment]
That var is defined like that in the Makefile, it has nothing to do with my system. But after two pull requests trying to solve this that have been closed, maybe it's time to move on...

**Comment by joscha** [comment]
For reference: https://github.com/TheThingsNetwork/ttn/blob/develop/Makefile#L9

**Comment by Sypheos** [comment]
govendor is not a part of the standard go library or tools it have to be manually installed on your system.
go get -u github.com/kardianos/govendor

The variable GO_PATH in the Makefile should not be used to access the real GOPATH as it's a modified version to fit our compilation need. Use $GOPATH insteadif you need to.

Also don't forget to set $GOBIN in your system or your shell ans add it to your $PATH variable

**Pull request closed without merging**
