### PR TITLE
allow ttnctl pf set to be non-interactive

### LINKED ISSUE #515: Non-Interactive version of "ttnctl applications pf set"
This is a **feature request** for **ttnctl**.

I am running
```console
ttnctl applications pf set converter "./src/ttn/converter.js"
```
from a build script and I always get prompted:
`Do you want to test the payload functions? (Y/n)`
however as it is an automated script, I'd like to disable this prompt: https://github.com/TheThingsNetwork/ttn/blob/ff54fc6b33763f800cf0a86ded8831bf30a88344/ttnctl/cmd/applications_pf_set.go#L160

So I wondered if such a flag can be added or whether I can contribute that and it would be merged.

## Environment
```
INFO Got build information                    Branch=master BuildDate=2017-02-08T11:11:20Z Commit=3c8b184a9a99573b93e89be9d7b2a3d284df376a Version=v2.5.1-dev
```

### PR DESCRIPTION
**Pull request by joscha**
Closes #515

### CODE REVIEW

**Comment by joscha** [comment]
@htdvisser any chance to get this in?

**Comment by htdvisser** [comment]
Merged in 8b8c14026b154d8319367849ff2536f3c349ac96

**Comment by joscha** [comment]
Thank you!

**Comment by joscha** [comment]
O, I just saw you changed it - would have been happy to bring it to a mergeable state @htdvisser.

**Comment by htdvisser** [comment]
No reason to delay this PR if I can fix it in one minute ;)

Thanks for your contribution!

**Pull request closed without merging**
